# This is a basic workflow to help you get started with Actions

name: client
on:
  pull_request:
    branches:
      - fe
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
    - name: Checkout source code.
      uses: actions/checkout@v3
    - name: Generate Environment Variables File for Production
      run: |
        echo "REACT_APP_BASE_URL=$REACT_APP_BASE_URL" >> .env.production.local
      env:
        REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      working-directory: ./client
    - name: Install dependencies
      run: npm install --force
      working-directory: ./client
    - name: Build
      run: npm run build
      working-directory: ./client
    - name: SHOW AWS CLI VERSION
      run: |
        aws --version
    - name: Sync Bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_EC2_METADATA_DISABLED: true
      run: |
        aws s3 sync \
          --region ap-northeast-2 \
          build s3://withskey.site \
          --delete
      working-directory: ./client
