INSERT INTO member(DISPLAY_NAME, EMAIL, OAUTH_TYPE) VALUES('moon full', 'fullmoon7813@gmail.com', 'google');
INSERT INTO member(DISPLAY_NAME, EMAIL, OAUTH_TYPE) VALUES('dahyun han', 'han2041126@gmail.com', 'google');
INSERT INTO member_roles(member_member_ID, ROLES) VALUES(1, 'USER');
INSERT INTO member_roles(member_member_ID, ROLES) VALUES(2, 'USER');
INSERT INTO member(member_ID,DISPLAY_NAME, EMAIL, OAUTH_TYPE) VALUES(100,'guest', 'guest@guest.com', 'google');
INSERT INTO member_roles(member_member_ID, ROLES) VALUES(100, 'USER');

INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (100, '제목1', '내용1', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (101, '제목2', '내용2', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (102, '제목3', '내용3', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (103, '제목4', '내용4', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (104, '제목5', '내용5', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (105, '제목6', '내용6', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (106, '제목7', '내용7', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (107, '제목8', '내용8', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (108, '제목9', '내용9', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (109, '제목10', '내용10', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (110, '제목11', '내용11', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (111, '제목12', '내용12', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (112, '제목13', '내용13', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (113, '제목14', '내용14', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (114, '제목15', '내용15', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (115, '제목16', '내용16', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (116, '제목17', '내용17', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (117, '제목18', '내용18', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (118, '제목19', '내용19', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (119, '제목20', '내용20', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (120, '제목21', '내용21', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (121, '제목22', '내용22', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (122, '제목23', '내용23', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (123, '제목24', '내용24', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (124, '제목25', '내용25', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (125, '제목26', '내용26', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (126, '제목27', '내용27', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (127, '제목28', '내용28', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (128, '제목29', '내용29', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (129, '제목30', '내용30', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (130, '제목31', '내용31', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (131, '제목32', '내용32', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (132, '제목33', '내용33', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (133, '제목34', '내용34', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (134, '제목35', '내용35', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (135, '제목36', '내용36', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (136, '제목37', '내용37', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (137, '제목38', '내용38', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (138, '제목39', '내용39', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (139, '제목40', '내용40', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (140, '제목41', '내용41', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (141, '제목42', '내용42', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (142, '제목43', '내용43', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (143, '제목44', '내용44', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (144, '제목45', '내용45', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (145, '제목46', '내용46', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (146, '제목47', '내용47', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (147, '제목48', '내용48', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (148, '제목49', '내용49', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (149, '제목50', '내용50', 1);
INSERT INTO board (board_ID, board_TITLE, CONTENT, member_ID) VALUES (150, '제목51', '내용51', 1);

INSERT INTO image(FILE_NAME, IMG_URL, board_ID) VALUES('캡처1.JPG','https://main-001-image.s3.ap-northeast-2.amazonaws.com/eae3d4b5-3f9d-4758-960d-483a8edba09c-%EC%BA%A1%EC%B2%98.JPG', 100);
INSERT INTO image(FILE_NAME, IMG_URL, board_ID) VALUES('캡처2.JPG','https://main-001-image.s3.ap-northeast-2.amazonaws.com/0061a0f5-e11f-434d-825c-791263d80434-%EC%BA%A1%EC%B2%98.JPG', 100);
