----Example for FE----
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (1, 121, 4);


---ONE SNACK Recommand---
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (2, 122, 4);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (3, 123, 1);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (4, 124, 3);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (5, 125, 2);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (6, 126, 5);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (7, 127, 5);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (8, 128, 6);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (9, 129, 3);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (10, 130, 4);

INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (11, 131, 1);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (12, 132, 5);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (13, 133, 6);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (14, 134, 8);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (15, 135, 2);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (16, 136, 3);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (17, 137, 5);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (18, 138, 1);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (19, 139, 2);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (20, 140, 3);

INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (21, 141, 1);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (22, 142, 7);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (23, 143, 6);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (24, 144, 5);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (25, 145, 3);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (26, 146, 4);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (27, 147, 3);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (28, 148, 2);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (29, 149, 1);
INSERT INTO SNACK_DRINK(SNACK_DRINK_ID, DRINK_ID, SNACK_ID) VALUES (30, 150, 8);