INSERT INTO SNACK (SNACK_ID, SNACK_IMAGE_URL, SNACK_INFO, SNACK_KCAL, SNACK_NAME) VALUES (100, 'snack1.jpg', 'Spicy Fried Chicken', 350, 'Chicken Wings');
INSERT INTO SNACK (SNACK_ID, SNACK_IMAGE_URL, SNACK_INFO, SNACK_KCAL, SNACK_NAME) VALUES (101, 'snack2.jpg', 'Cheesy Nachos', 500, 'Nachos');
INSERT INTO SNACK (SNACK_ID, SNACK_IMAGE_URL, SNACK_INFO, SNACK_KCAL, SNACK_NAME) VALUES (102, 'snack3.jpg', 'Classic Potato Chips', 150, 'Potato Chips');
INSERT INTO SNACK (SNACK_ID, SNACK_IMAGE_URL, SNACK_INFO, SNACK_KCAL, SNACK_NAME) VALUES (103, 'snack4.jpg', 'Mixed Nuts', 200, 'Assorted Nuts');
INSERT INTO SNACK (SNACK_ID, SNACK_IMAGE_URL, SNACK_INFO, SNACK_KCAL, SNACK_NAME) VALUES (104, 'snack5.jpg', 'Garlic Fries', 400, 'French Fries');
