-- ---- Example For FE----
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (1, 121, 7);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (2, 121, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (3, 122, 7);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (4, 123, 7);

----Single----
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (5, 121, 24);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (6, 122, 24);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (7, 123, 24);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (8, 124, 24);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (9, 125, 24);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (10, 126,24);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (11, 127,24);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (12, 128,24);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (13, 129,24);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (14, 130,24);

----Blended----
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (15, 131, 20);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (16, 132, 20);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (17, 133, 20);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (18, 134, 20);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (19, 135, 20);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (20, 136, 20);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (21, 137, 20);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (22, 138, 20);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (23, 139, 20);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (24, 140, 20);

----Bourbon----
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (25, 141, 22);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (26, 142, 22);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (27, 143, 22);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (28, 144, 22);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (29, 145, 22);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (30, 146, 22);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (31, 147, 22);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (32, 148, 22);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (33, 149, 22);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (34, 150, 22);

----Entry----
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (35, 121, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (36, 122, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (37, 123, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (38, 124, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (39, 125, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (40, 126, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (41, 127, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (42, 128, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (43, 129, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (44, 130, 9);
--
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (45, 131, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (46, 132, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (47, 133, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (48, 134, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (49, 135, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (50, 136, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (51, 137, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (52, 138, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (53, 139, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (54, 140, 9);
--
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (55, 141, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (56, 142, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (57, 143, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (58, 144, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (59, 145, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (60, 146, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (61, 147, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (62, 148, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (63, 149, 9);
-- INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (64, 150, 9);

---SNACK TAGGING---
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (65, 121, 33);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (66, 122, 33);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (67, 123, 29);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (68, 124, 31);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (69, 125, 30);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (70, 126, 34);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (71, 127, 34);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (72, 128, 35);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (73, 129, 31);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (74, 130, 33);

INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (75, 131, 29);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (76, 132, 34);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (77, 133, 35);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (78, 134, 37);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (79, 135, 30);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (80, 136, 31);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (81, 137, 34);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (82, 138, 29);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (83, 139, 30);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (84, 140, 31);

INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (85, 141, 29);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (86, 142, 36);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (87, 143, 35);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (88, 144, 34);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (89, 145, 31);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (90, 146, 33);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (91, 147, 31);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (92, 148, 30);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (93, 149, 29);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (94, 150, 37);

--- Situation Tag ---
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (95, 121, 1);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (96, 122, 2);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (97, 123, 1);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (98, 124, 4);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (99, 125, 5);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (100, 126, 2);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (101, 127, 1);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (102, 128, 7);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (103, 129, 8);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (104, 130, 7);

INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (105, 131, 2);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (106, 132, 3);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (107, 133, 4);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (108, 134, 5);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (109, 135, 6);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (110, 136, 5);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (111, 137, 4);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (112, 138, 2);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (113, 139, 1);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (114, 140, 6);

INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (115, 141, 8);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (116, 142, 7);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (117, 143, 2);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (118, 144, 3);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (119, 145, 5);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (120, 146, 4);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (121, 147, 5);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (122, 148, 1);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (123, 149, 2);
INSERT INTO tag_drink(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (124, 150, 4);