---- Example For FE----
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (1, 121, 7);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (2, 121, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (3, 122, 7);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (4, 123, 7);


----Single----
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (5, 121, 24);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (6, 122, 24);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (7, 123, 24);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (8, 124, 24);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (9, 125, 24);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (10, 126,24);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (11, 127,24);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (12, 128,24);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (13, 129,24);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (14, 130,24);

----Blended----
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (15, 131, 20);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (16, 132, 20);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (17, 133, 20);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (18, 134, 20);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (19, 135, 20);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (20, 136, 20);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (21, 137, 20);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (22, 138, 20);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (23, 139, 20);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (24, 140, 20);


----Bourbon----
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (25, 141, 22);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (26, 142, 22);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (27, 143, 22);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (28, 144, 22);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (29, 145, 22);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (30, 146, 22);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (31, 147, 22);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (32, 148, 22);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (33, 149, 22);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (34, 150, 22);

----Enyry----
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (35, 121, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (36, 122, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (37, 123, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (38, 124, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (39, 125, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (40, 126, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (41, 127, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (42, 128, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (43, 129, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (44, 130, 9);

INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (45, 131, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (46, 132, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (47, 133, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (48, 134, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (49, 135, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (50, 136, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (51, 137, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (52, 138, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (53, 139, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (54, 140, 9);

INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (55, 141, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (56, 142, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (57, 143, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (58, 144, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (59, 145, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (60, 146, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (61, 147, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (62, 148, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (63, 149, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (64, 150, 9);