INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (1, 121, 7);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (2, 121, 9);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (3, 122, 7);
INSERT INTO TAG_DRINK(TAG_DRINK_ID, DRINK_ID, TAG_ID) VALUES (4, 123, 7);